Milkrun/Web(Backend)/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Admin Routes

Route::prefix('admin')->group(function () {
    Route::get('/', ['as' => 'admin.login', 'uses' => 'Auth\AdminLoginController@showLoginForm']);
    Route::post('/login', ['as' => 'admin.login.submit', 'uses' => 'Auth\AdminLoginController@login']);
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@index']);
        Route::get('/change-language/{locale}', ['as' => 'admin.language', 'uses' => 'Admin\AdminController@SetLangauge']);
        Route::get('/logout', ['as' => 'admin.logout', 'uses' => 'Auth\AdminLoginController@logout']);
        Route::resource('documents', 'Admin\DocumentController');
        Route::post('document/update', ['as' => 'doc.update', 'uses' => 'Admin\DocumentController@update']);
        Route::resource('cms', 'Admin\CmsPagesController');
        Route::post('/cms/search', ['as' => 'admin.cms.search', 'uses' => 'Admin\CmsPagesController@Search']);

        Route::resource('promotions', 'Admin\PromotionNotificationController');
        Route::post('/promotions/search', ['as' => 'promotions.search', 'uses' => 'Admin\PromotionNotificationController@Search']);

        Route::get('/onesignal', ['as' => 'onesignal.index', 'uses' => 'Admin\AdminController@OneSignal']);
        Route::post('/onesignal', ['as' => 'onesignal.store', 'uses' => 'Admin\AdminController@UpdateOneSignal']);

        Route::get('/customer_support', ['as' => 'customer_support.index', 'uses' => 'Admin\AdminController@Customer_Support']);
        Route::post('/customer_support', ['as' => 'customer_support.search', 'uses' => 'Admin\AdminController@Customer_Support_Search']);

//Retailer
        Route::resource('retailer', 'Admin\RetailerController');
        Route::get('/retailer/wallet/{id}', ['as' => 'retailer.wallet', 'uses' => 'Admin\RetailerController@Wallet']);
        Route::post('/retailer/addmoney', ['as' => 'retailer.add.wallet', 'uses' => 'Admin\RetailerController@AddWalletMoney']);
        Route::get('/retailer/active/deactive/{id}/{status}', ['as' => 'retailer.active-deactive', 'uses' => 'Admin\RetailerController@ChangeStatus']);
        Route::post('/search/retailer', ['as' => 'retailer.search', 'uses' => 'Admin\RetailerController@Serach']);

//Driver
        Route::resource('drivers', 'Admin\DriverController');
        Route::get('/driver/wallet/{id}', ['as' => 'driver.wallet', 'uses' => 'Admin\DriverController@Wallet']);
        Route::post('/driver/addmoney', ['as' => 'driver.add.wallet', 'uses' => 'Admin\DriverController@AddWalletMoney']);
        Route::get('/driver/active/deactive/{id}/{status}', ['as' => 'driver.active-deactive', 'uses' => 'Admin\DriverController@ChangeStatus']);
        Route::post('/search/driver', ['as' => 'driver.search', 'uses' => 'Admin\DriverController@Serach']);

//Customer
        Route::resource('customers', 'Admin\CustomersController');
        Route::get('/customer/wallet/{id}', ['as' => 'customer.wallet', 'uses' => 'Admin\CustomersController@Wallet']);
        Route::post('/customer/addmoney', ['as' => 'customer.add.wallet', 'uses' => 'Admin\CustomersController@AddWalletMoney']);
        Route::get('/customer/active/deactive/{id}/{status}', ['as' => 'customer.active-deactive', 'uses' => 'Admin\CustomersController@ChangeStatus']);
        Route::post('/search/customer', ['as' => 'customer.search', 'uses' => 'Admin\CustomersController@Serach']);

//OrdersManagement
            Route::resource('orders', 'Admin\OrderManagementController');

//Station
        Route::resource('stations', 'Admin\StationController');
        Route::get('/station/wallet/{id}', ['as' => 'station.wallet', 'uses' => 'Admin\StationController@Wallet']);
        Route::post('/station/addmoney', ['as' => 'station.add.wallet', 'uses' => 'Admin\StationController@AddWalletMoney']);
        Route::get('/station/active/deactive/{id}/{status}', ['as' => 'station.active-deactive', 'uses' => 'Admin\StationController@ChangeStatus']);
        Route::post('/search/station', ['as' => 'station.search', 'uses' => 'Admin\StationController@Serach']);

//Station
        Route::resource('measurements', 'Admin\MeasurementController');
        Route::get('/measurement/wallet/{id}', ['as' => 'measurement.wallet', 'uses' => 'Admin\MeasurementController@Wallet']);
        Route::post('/measurement/addmoney', ['as' => 'measurement.add.wallet', 'uses' => 'Admin\MeasurementController@AddWalletMoney']);
        Route::get('/measurement/active/deactive/{id}/{status}', ['as' => 'measurement.active-deactive', 'uses' => 'Admin\MeasurementController@ChangeStatus']);
        Route::post('/search/measurement', ['as' => 'measurement.search', 'uses' => 'Admin\MeasurementController@Serach']);

    });
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Milkrun/Web(Backend)/resources/views/admin/promotion/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">

            <div class="content-header row">
                <div class="content-header-left col-md-4 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.message62')</h3>
                </div>
                <div class="col-md-6 col-12">
                    @if(session('notification'))
                        <div class="col-md-6 alert alert-icon-right alert-info alert-dismissible mb-2" role="alert">
                            <span class="alert-icon"><i class="fa fa-info"></i></span>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <strong>@lang('admin.message76')</strong>
                        </div>
                    @endif
                </div>
                <div class="content-header-right col-md-2 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('promotions.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="basic-tabs-components">
                    <div class="row match-height">
                        <div class="col-lg-8">
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                        <ul class="nav nav-tabs nav-top-border no-hover-bg">
                                            <li class="nav-item">
                                                <a class="nav-link active" id="base-tab11" data-toggle="tab"
                                                   aria-controls="tab11" href="#tab11" aria-expanded="true"><i
                                                            class="fa fa-users"></i>@lang('admin.message301')</a>
                                            </li>
                                        </ul>
                                        <div class="tab-content px-1 pt-1">
                                            <div role="tabpanel" class="tab-pane active" id="tab11" aria-expanded="true"
                                                 aria-labelledby="base-tab11">
                                                <form method="POST" class="steps-validation wizard-notification"
                                                      enctype="multipart/form-data" action="{{ route('promotions.store') }}">
                                                    @csrf
                                                    <fieldset>


                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="location3">@lang('admin.message67') :</label>
                                                                    <select class="form-control" name="application"
                                                                            id="application" onchange="DriverNotification(this.value)" required>
                                                                        <option value="">--@lang('admin.message72')--</option>
                                                                        <option value="1">@lang('admin.message69')</option>
                                                                        <option value="2">@lang('admin.message70')</option>
                                                                    </select>

                                                                    @if ($errors->has('application'))
                                                                        <label class="danger">{{ $errors->first('application') }}</label>
                                                                    @endif
                                                                </div>
                                                            </div>

                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="lastName3">
                                                                        @lang('admin.message63') :
                                                                        <span class="danger">*</span>
                                                                    </label>
                                                                    <input type="text" class="form-control" id="title"
                                                                           name="title"
                                                                           placeholder="@lang('admin.message63')" required>
                                                                    @if ($errors->has('title'))
                                                                        <label class="danger">{{ $errors->first('title') }}</label>
                                                                    @endif
                                                                </div>
                                                            </div>
                                                        </div>


                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="emailAddress5">
                                                                        @lang('admin.message64') :
                                                                        <span class="danger">*</span>
                                                                    </label>
                                                                    <textarea class="form-control" id="message" name="message"
                                                                              rows="3"
                                                                              placeholder="@lang('admin.message64')"></textarea>
                                                                    @if ($errors->has('message'))
                                                                        <label class="danger">{{ $errors->first('message') }}</label>
                                                                    @endif
                                                                </div>
                                                            </div>

                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="ProfileImage">
                                                                        @lang('admin.message65') :
                                                                        <span class="danger">*</span>
                                                                    </label>
                                                                    <input type="file" class="form-control" id="image"
                                                                           name="image"
                                                                           placeholder="@lang('admin.message65')" required>
                                                                    @if ($errors->has('image'))
                                                                        <label class="danger">{{ $errors->first('image') }}</label>
                                                                    @endif
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="emailAddress5">
                                                                        @lang('admin.message66') :
                                                                        <span class="danger">*</span>
                                                                    </label>
                                                                    <input type="url" class="form-control" id="url"
                                                                           name="url"
                                                                           placeholder="@lang('admin.message66')" required>
                                                                    @if ($errors->has('url'))
                                                                        <label class="danger">{{ $errors->first('url') }}</label>
                                                                    @endif
                                                                </div>
                                                            </div>

                                                            {{--<div class="col-md-6">--}}
                                                            {{--<div class="form-group">--}}
                                                            {{--<label for="location3">@lang('admin.message73') :</label>--}}
                                                            {{--<select class="form-control" name="application"--}}
                                                            {{--id="application" required>--}}
                                                            {{--<option value="1">@lang('admin.message74')</option>--}}
                                                            {{--<option value="2">@lang('admin.message75')</option>--}}
                                                            {{--</select>--}}

                                                            {{--@if ($errors->has('application'))--}}
                                                            {{--<label class="danger">{{ $errors->first('application') }}</label>--}}
                                                            {{--@endif--}}
                                                            {{--</div>--}}
                                                            {{--</div>--}}

                                                        </div>

                                                    </fieldset>
                                                    <div class="form-actions right">
                                                        <button type="submit" class="btn btn-primary">
                                                            <i class="fa fa-check-square-o"></i> Save
                                                        </button>
                                                    </div>
                                                </form>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection

Milkrun/Web(Backend)/resources/views/admin/promotion/edit.blade.php
@extends('merchant.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">

            <div class="content-header row">
                <div class="content-header-left col-md-4 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.message422')</h3>
                </div>
                <div class="col-md-6 col-12">
                    @if(session('notification'))
                        <div class="col-md-6 alert alert-icon-right alert-info alert-dismissible mb-2" role="alert">
                            <span class="alert-icon"><i class="fa fa-info"></i></span>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <strong>@lang('admin.message423')</strong>
                        </div>
                    @endif
                </div>
                <div class="content-header-right col-md-2 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('promotions.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="validation">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                        <form method="POST" class="steps-validation wizard-notification"
                                              enctype="multipart/form-data"
                                              action="{{route('promotions.update', $promotion->id)}}">
                                            {{method_field('PUT')}}
                                            @csrf
                                            <fieldset>
                                                <div class="row">

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="lastName3">
                                                                @lang('admin.message63') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="title"
                                                                   name="title"
                                                                   placeholder="@lang('admin.message63')" value="{{ $promotion->title }}" required>
                                                            @if ($errors->has('title'))
                                                                <label class="danger">{{ $errors->first('title') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message64') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <textarea class="form-control" id="message" name="message"
                                                                      rows="3"
                                                                      placeholder="@lang('admin.message64')">{{ $promotion->message }}</textarea>
                                                            @if ($errors->has('message'))
                                                                <label class="danger">{{ $errors->first('message') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="ProfileImage">
                                                                @lang('admin.message65') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="file" class="form-control" id="image"
                                                                   name="image"
                                                                   placeholder="@lang('admin.message65')">
                                                            @if ($errors->has('image'))
                                                                <label class="danger">{{ $errors->first('image') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message66') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="url" class="form-control" id="url"
                                                                   name="url"
                                                                   placeholder="@lang('admin.message66')" value="{{ $promotion->url }}" required>
                                                            @if ($errors->has('url'))
                                                                <label class="danger">{{ $errors->first('url') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>

                                                </div>


                                            </fieldset>
                                            <div class="form-actions right">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fa fa-check-square-o"></i> Save
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
@endsection