Milkrun/Web(Backend)/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Admin Routes

Route::prefix('admin')->group(function () {
    Route::get('/', ['as' => 'admin.login', 'uses' => 'Auth\AdminLoginController@showLoginForm']);
    Route::post('/login', ['as' => 'admin.login.submit', 'uses' => 'Auth\AdminLoginController@login']);
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@index']);
        Route::get('/change-language/{locale}', ['as' => 'admin.language', 'uses' => 'Admin\AdminController@SetLangauge']);
        Route::get('/logout', ['as' => 'admin.logout', 'uses' => 'Auth\AdminLoginController@logout']);
        Route::resource('documents', 'Admin\DocumentController');
        Route::post('document/update', ['as' => 'doc.update', 'uses' => 'Admin\DocumentController@update']);
        Route::resource('cms', 'Admin\CmsPagesController');
        Route::post('/cms/search', ['as' => 'admin.cms.search', 'uses' => 'Admin\CmsPagesController@Search']);

        Route::resource('promotions', 'Admin\PromotionNotificationController');
        Route::post('/promotions/search', ['as' => 'promotions.search', 'uses' => 'Admin\PromotionNotificationController@Search']);

        Route::get('/onesignal', ['as' => 'onesignal.index', 'uses' => 'Admin\AdminController@OneSignal']);
        Route::post('/onesignal', ['as' => 'onesignal.store', 'uses' => 'Admin\AdminController@UpdateOneSignal']);

        Route::get('/customer_support', ['as' => 'customer_support.index', 'uses' => 'Admin\AdminController@Customer_Support']);
        Route::post('/customer_support', ['as' => 'customer_support.search', 'uses' => 'Admin\AdminController@Customer_Support_Search']);

//Retailer
        Route::resource('retailer', 'Admin\RetailerController');
        Route::get('/retailer/wallet/{id}', ['as' => 'retailer.wallet', 'uses' => 'Admin\RetailerController@Wallet']);
        Route::post('/retailer/addmoney', ['as' => 'retailer.add.wallet', 'uses' => 'Admin\RetailerController@AddWalletMoney']);
        Route::get('/retailer/active/deactive/{id}/{status}', ['as' => 'retailer.active-deactive', 'uses' => 'Admin\RetailerController@ChangeStatus']);
        Route::post('/search/retailer', ['as' => 'retailer.search', 'uses' => 'Admin\RetailerController@Serach']);

//Driver
        Route::resource('drivers', 'Admin\DriverController');
        Route::get('/driver/wallet/{id}', ['as' => 'driver.wallet', 'uses' => 'Admin\DriverController@Wallet']);
        Route::post('/driver/addmoney', ['as' => 'driver.add.wallet', 'uses' => 'Admin\DriverController@AddWalletMoney']);
        Route::get('/driver/active/deactive/{id}/{status}', ['as' => 'driver.active-deactive', 'uses' => 'Admin\DriverController@ChangeStatus']);
        Route::post('/search/driver', ['as' => 'driver.search', 'uses' => 'Admin\DriverController@Serach']);

//Customer
        Route::resource('customers', 'Admin\CustomersController');
        Route::get('/customer/wallet/{id}', ['as' => 'customer.wallet', 'uses' => 'Admin\CustomersController@Wallet']);
        Route::post('/customer/addmoney', ['as' => 'customer.add.wallet', 'uses' => 'Admin\CustomersController@AddWalletMoney']);
        Route::get('/customer/active/deactive/{id}/{status}', ['as' => 'customer.active-deactive', 'uses' => 'Admin\CustomersController@ChangeStatus']);
        Route::post('/search/customer', ['as' => 'customer.search', 'uses' => 'Admin\CustomersController@Serach']);

//OrdersManagement
            Route::resource('orders', 'Admin\OrderManagementController');

//Station
        Route::resource('stations', 'Admin\StationController');
        Route::get('/station/wallet/{id}', ['as' => 'station.wallet', 'uses' => 'Admin\StationController@Wallet']);
        Route::post('/station/addmoney', ['as' => 'station.add.wallet', 'uses' => 'Admin\StationController@AddWalletMoney']);
        Route::get('/station/active/deactive/{id}/{status}', ['as' => 'station.active-deactive', 'uses' => 'Admin\StationController@ChangeStatus']);
        Route::post('/search/station', ['as' => 'station.search', 'uses' => 'Admin\StationController@Serach']);

//Station
        Route::resource('measurements', 'Admin\MeasurementController');
        Route::get('/measurement/wallet/{id}', ['as' => 'measurement.wallet', 'uses' => 'Admin\MeasurementController@Wallet']);
        Route::post('/measurement/addmoney', ['as' => 'measurement.add.wallet', 'uses' => 'Admin\MeasurementController@AddWalletMoney']);
        Route::get('/measurement/active/deactive/{id}/{status}', ['as' => 'measurement.active-deactive', 'uses' => 'Admin\MeasurementController@ChangeStatus']);
        Route::post('/search/measurement', ['as' => 'measurement.search', 'uses' => 'Admin\MeasurementController@Serach']);

    });
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Milkrun/Web(Backend)/app/Models/Measurement.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Measurement extends Model
{
    protected $guarded = [];
}

Milkrun/Web(Backend)/app/Http/Controllers/Admin/MeasurementController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Measurement;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class MeasurementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $measurements = Measurement::get();
        return view('admin.measurements.index', compact('measurements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Measurement  $measurement
     * @return \Illuminate\Http\Response
     */
    public function show(Measurement $measurement)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Measurement  $measurement
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $measurement = Measurement::findOrFail($id);
        return view('admin.measurements.edit', compact('measurement'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Measurement  $measurement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'measure_unit_name' => "required",
            'measure_unit' => "required",
            'measure_unit_value' => "required",
        ]);
        $measurement = Measurement::findOrFail($id);
        $measurement->measure_unit_name = $request->measure_unit_name;
        $measurement->measure_unit = $request->measure_unit;
        $measurement->measure_unit_value = $request->measure_unit_value;
        $measurement->save();
        return redirect()->back()->with('measureupdated', 'Details Updated Added');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Measurement  $measurement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Measurement $measurement)
    {
        //
    }

    public function ChangeStatus($id, $status)
    {
        $validator = Validator::make(
            [
                'id' => $id,
                'status' => $status,
            ],
            [
                'id' => ['required'],
                'status' => ['required', 'integer', 'between:1,2'],
            ]);
        if ($validator->fails()) {
            return redirect()->back();
        }
        $measurement = Measurement::findOrFail($id);
        $measurement->measure_unit_status = $status;
        $measurement->save();
        return redirect()->back();
    }


}

Milkrun/Web(Backend)/resources/views/admin/measurements/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">

            <div class="content-header row">
                <div class="content-header-left col-md-4 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.melvin_measurement_edit_message1')</h3>
                </div>
                <div class="col-md-6 col-12">
                    @if(session('measureupdated'))
                        <div class="col-md-6 alert alert-icon-right alert-info alert-dismissible mb-2" role="alert">
                            <span class="alert-icon"><i class="fa fa-info"></i></span>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <strong>@lang('admin.melvin_measurement_edit_message9')</strong>
                        </div>
                    @endif
                </div>
                <div class="content-header-right col-md-2 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('measurements.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="validation">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                        <form method="POST" class="steps-validation wizard-notification"
                                              enctype="multipart/form-data"
                                              action="{{route('measurements.update', $measurement->id)}}">
                                            {{method_field('PUT')}}
                                            @csrf
                                            <fieldset>
                                                <div class="row">
                                                    <div class="col-md-9">
                                                        <div class="form-group">
                                                            <label for="measure_unit_name">
                                                                @lang('admin.melvin_measurement_edit_message3') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="measure_unit_name"
                                                                   name="measure_unit_name" value="{{$measurement->measure_unit_name}}"
                                                                   placeholder="@lang('admin.melvin_measurement_edit_message3')" required>
                                                            @if ($errors->has('measure_unit_name'))
                                                                <label class="danger">{{ $errors->first('measure_unit_name') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>


                                                    <div class="col-md-9">
                                                        <div class="form-group">
                                                            <label for="measure_unit">
                                                                @lang('admin.melvin_measurement_edit_message8') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="measure_unit"
                                                                   name="measure_unit" value="{{$measurement->measure_unit}}"
                                                                   placeholder="@lang('admin.melvin_measurement_edit_message8')" required>
                                                            @if ($errors->has('measure_unit'))
                                                                <label class="danger">{{ $errors->first('measure_unit') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-9">
                                                        <div class="form-group">
                                                            <label for="measure_unit_value">
                                                                @lang('admin.melvin_measurement_edit_message4') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="measure_unit_value"
                                                                   name="measure_unit_value"
                                                                   placeholder="@lang('admin.melvin_measurement_edit_message4')"
                                                                   value="{{$measurement->measure_unit_value}}" required>
                                                            @if ($errors->has('measure_unit_value'))
                                                                <label class="danger">{{ $errors->first('measure_unit_value') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>

                                            </fieldset>
                                            <div class="form-actions right">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fa fa-check-square-o"></i> @lang('admin.melvin_retailer_edit_message11')
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
    <script>
        function EditPassword() {
            if (document.getElementById("edit_password").checked = true) {
                document.getElementById('password').disabled = false;
            }
        }

    </script>
@endsection

Milkrun/Web(Backend)/resources/views/admin/measurements/favourite-drivers.blade.php
@extends('merchant.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-8 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">{{ $user->UserName }} @lang('admin.message13')</h3>
                </div>
                <div class="content-header-right col-md-4 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('retailer.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section id="user-profile-cards-with-stats" class="row mt-2">
                    @foreach($user->FavouriteDriver as $driver)
                        <div class="col-xl-4 col-md-6 col-12">
                            <div class="card profile-card-with-stats">
                                <div class="text-center">
                                    <div class="card-body">
                                        <img src="{{ asset($driver->Driver->profile_image) }}"
                                             class="rounded-circle  height-150"
                                             alt="Card image">
                                    </div>
                                    <div class="card-body">
                                        <h4 class="card-title">{{ $driver->Driver->fullName }}</h4>
                                        <h4 class="card-title">{{ $driver->Driver->phoneNumber }}</h4>
                                        <h4 class="card-title">{{ $driver->Driver->email }}</h4>
                                    </div>
                                    <div class="card-body">
                                        <p>{{ $driver->Driver->CountryArea->AreaName}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </section>


            </div>
        </div>
    </div>
@endsection

Milkrun/Web(Backend)/resources/views/admin/measurements/favourite.blade.php
@extends('merchant.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-8 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">{{ $user->UserName }} @lang('admin.message5')</h3>

                </div>
                <div class="content-header-right col-md-4 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('retailer.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="content-body">

                <section id="horizontal">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                        <table class="table display nowrap table-striped table-bordered scroll-horizontal">
                                            <thead>
                                            <tr>
                                                <th>@lang('admin.message5')</th>
                                                <th>@lang('admin.message6')</th>
                                                <th>@lang('admin.message12')</th>
                                                <th>@lang('admin.message7')</th>
                                                <th>@lang('admin.message8')</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($user->FavouriteLocation as $location)
                                                <tr>
                                                    <td>{{ $location->location }}</td>
                                                    @switch($location->category)
                                                        @case(1)
                                                        <td>@lang('admin.message9')</td>
                                                        @break
                                                        @case(2)
                                                        <td>@lang('admin.message10')</td>
                                                        @break
                                                        @case(3)
                                                        <td>@lang('admin.message11')</td>
                                                        @break
                                                    @endswitch
                                                    <td>
                                                        @if($location->other_name)
                                                           {{ $location->other_name }}
                                                        @else
                                                            ------
                                                        @endif
                                                    </td>
                                                    <td>{{ $location->created_at }}</td>
                                                    <td>{{ $location->updated_at }}</td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
@endsection

Milkrun/Web(Backend)/resources/views/admin/measurements/index.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-4 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.melvin_measurement_message1')</h3>
                </div>

                <div class="col-md-6 col-12">
                    @if(session('moneyAdded'))
                        <div class="col-md-8 alert alert-icon-right alert-info alert-dismissible mb-2" role="alert">
                            <span class="alert-icon"><i class="fa fa-info"></i></span>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <strong>@lang('admin.message430')</strong>
                        </div>
                    @endif
                </div>


                <!--<div class="content-header-right col-md-2 col-12">-->
                <!--    <div class="btn-group float-md-right">-->
                <!--        <div class="heading-elements">-->
                <!--            <a href="{{route('retailer.create')}}">-->
                <!--                <button type="button" class="btn btn-icon btn-success mr-1"><i-->
                <!--                        class="fa fa-plus"></i>-->
                <!--                </button>-->
                <!--            </a>-->
                <!--        </div>-->
                <!--    </div>-->
                <!--</div>-->

            </div>
            <div class="content-body">
                <section id="horizontal">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">

                                <div class="card-content collapse show">
                                    <div class="">
                                        <table
                                            class="table display nowrap table-striped table-bordered scroll-horizontal">
                                            <thead>
                                            <tr>
                                                <th>@lang('admin.melvin_measurement_message2')</th>
                                                <th>@lang('admin.melvin_measurement_message3')</th>
                                                <th>@lang('admin.melvin_measurement_message8')</th>
                                                <th>@lang('admin.melvin_measurement_message4')</th>
                                                <th>@lang('admin.melvin_measurement_message5')</th>
                                                <th>@lang('admin.melvin_measurement_message7')</th>
                                                <th>@lang('admin.created_at')</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($measurements as $measurement)
                                                <tr>
                                                    <td>{{ $measurement->id }}</td>
                                                    <td>{{ $measurement->measure_unit_name }}</td>
                                                    <td>{{ $measurement->measure_unit }}</td>
                                                    <td>{{ $measurement->measure_unit_value }}</td>
                                                    <td>
                                                        @if($measurement->measure_unit_status == 1)
                                                            <label class="label_success">@lang('admin.active')</label>
                                                        @else
                                                            <label class="label_danger">@lang('admin.deactive')</label>
                                                        @endif
                                                    </td>

                                                    <td>

                                                        <a href="{{ route('measurements.edit',$measurement->id) }}"
                                                           data-original-title="Edit" data-toggle="tooltip"
                                                           data-placement="top"
                                                           class="btn menu-icon btn_edit action_btn"> <i
                                                                class="fa fa-pencil"></i> </a>

                                                        @if($measurement->measure_unit_status == 1)
                                                            <a href="{{ route('measurement.active-deactive',['id'=>$measurement->id,'status'=>2]) }}"
                                                               data-original-title="Inactive" data-toggle="tooltip"
                                                               data-placement="top"
                                                               class="btn menu-icon btn_eye_dis action_btn"> <i
                                                                    class="fa fa-eye-slash"></i> </a>
                                                        @else
                                                            <a href="{{ route('measurement.active-deactive',['id'=>$measurement->id,'status'=>1]) }}"
                                                               data-original-title="Active" data-toggle="tooltip"
                                                               data-placement="top"
                                                               class="btn menu-icon btn_eye action_btn"> <i
                                                                    class="fa fa-eye"></i> </a>
                                                        @endif
                                                    </td>
                                                    <td>{{ $measurement->created_at->toformatteddatestring() }}</td>
                                                </tr>

                                            @endforeach

                                            </tbody>

                                        </table>
                                    </div>
                                </div>
                                {{--<div class="col-sm-12">--}}
                                    {{--<div class="pagination1">{{ $measurements->links() }}</div>--}}
                                {{--</div>--}}
                            </div>

                        </div>
                    </div>

                </section>

            </div>
        </div>
    </div>

@endsection