Milkrun/Web(Backend)/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Admin Routes

Route::prefix('admin')->group(function () {
    Route::get('/', ['as' => 'admin.login', 'uses' => 'Auth\AdminLoginController@showLoginForm']);
    Route::post('/login', ['as' => 'admin.login.submit', 'uses' => 'Auth\AdminLoginController@login']);
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@index']);
        Route::get('/change-language/{locale}', ['as' => 'admin.language', 'uses' => 'Admin\AdminController@SetLangauge']);
        Route::get('/logout', ['as' => 'admin.logout', 'uses' => 'Auth\AdminLoginController@logout']);
        Route::resource('documents', 'Admin\DocumentController');
        Route::post('document/update', ['as' => 'doc.update', 'uses' => 'Admin\DocumentController@update']);
        Route::resource('cms', 'Admin\CmsPagesController');
        Route::post('/cms/search', ['as' => 'admin.cms.search', 'uses' => 'Admin\CmsPagesController@Search']);

        Route::resource('promotions', 'Admin\PromotionNotificationController');
        Route::post('/promotions/search', ['as' => 'promotions.search', 'uses' => 'Admin\PromotionNotificationController@Search']);

        Route::get('/onesignal', ['as' => 'onesignal.index', 'uses' => 'Admin\AdminController@OneSignal']);
        Route::post('/onesignal', ['as' => 'onesignal.store', 'uses' => 'Admin\AdminController@UpdateOneSignal']);

        Route::get('/customer_support', ['as' => 'customer_support.index', 'uses' => 'Admin\AdminController@Customer_Support']);
        Route::post('/customer_support', ['as' => 'customer_support.search', 'uses' => 'Admin\AdminController@Customer_Support_Search']);

//Retailer
        Route::resource('retailer', 'Admin\RetailerController');
        Route::get('/retailer/wallet/{id}', ['as' => 'retailer.wallet', 'uses' => 'Admin\RetailerController@Wallet']);
        Route::post('/retailer/addmoney', ['as' => 'retailer.add.wallet', 'uses' => 'Admin\RetailerController@AddWalletMoney']);
        Route::get('/retailer/active/deactive/{id}/{status}', ['as' => 'retailer.active-deactive', 'uses' => 'Admin\RetailerController@ChangeStatus']);
        Route::post('/search/retailer', ['as' => 'retailer.search', 'uses' => 'Admin\RetailerController@Serach']);

//Driver
        Route::resource('drivers', 'Admin\DriverController');
        Route::get('/driver/wallet/{id}', ['as' => 'driver.wallet', 'uses' => 'Admin\DriverController@Wallet']);
        Route::post('/driver/addmoney', ['as' => 'driver.add.wallet', 'uses' => 'Admin\DriverController@AddWalletMoney']);
        Route::get('/driver/active/deactive/{id}/{status}', ['as' => 'driver.active-deactive', 'uses' => 'Admin\DriverController@ChangeStatus']);
        Route::post('/search/driver', ['as' => 'driver.search', 'uses' => 'Admin\DriverController@Serach']);

//Customer
        Route::resource('customers', 'Admin\CustomersController');
        Route::get('/customer/wallet/{id}', ['as' => 'customer.wallet', 'uses' => 'Admin\CustomersController@Wallet']);
        Route::post('/customer/addmoney', ['as' => 'customer.add.wallet', 'uses' => 'Admin\CustomersController@AddWalletMoney']);
        Route::get('/customer/active/deactive/{id}/{status}', ['as' => 'customer.active-deactive', 'uses' => 'Admin\CustomersController@ChangeStatus']);
        Route::post('/search/customer', ['as' => 'customer.search', 'uses' => 'Admin\CustomersController@Serach']);

//OrdersManagement
            Route::resource('orders', 'Admin\OrderManagementController');

//Station
        Route::resource('stations', 'Admin\StationController');
        Route::get('/station/wallet/{id}', ['as' => 'station.wallet', 'uses' => 'Admin\StationController@Wallet']);
        Route::post('/station/addmoney', ['as' => 'station.add.wallet', 'uses' => 'Admin\StationController@AddWalletMoney']);
        Route::get('/station/active/deactive/{id}/{status}', ['as' => 'station.active-deactive', 'uses' => 'Admin\StationController@ChangeStatus']);
        Route::post('/search/station', ['as' => 'station.search', 'uses' => 'Admin\StationController@Serach']);

//Station
        Route::resource('measurements', 'Admin\MeasurementController');
        Route::get('/measurement/wallet/{id}', ['as' => 'measurement.wallet', 'uses' => 'Admin\MeasurementController@Wallet']);
        Route::post('/measurement/addmoney', ['as' => 'measurement.add.wallet', 'uses' => 'Admin\MeasurementController@AddWalletMoney']);
        Route::get('/measurement/active/deactive/{id}/{status}', ['as' => 'measurement.active-deactive', 'uses' => 'Admin\MeasurementController@ChangeStatus']);
        Route::post('/search/measurement', ['as' => 'measurement.search', 'uses' => 'Admin\MeasurementController@Serach']);

    });
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Milkrun/Web(Backend)/resources/views/admin/cms/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/summernote.css') }}">
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-8 col-12 mb-2 ">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.message209') (@lang('admin.message459') {{ strtoupper(Config::get('app.locale')) }})</h3>
                </div>
                <div class="content-header-right col-md-4 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('cms.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <section id="validation">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                        <form method="POST" class="steps-validation wizard-notification"
                                              enctype="multipart/form-data" action="{{ route('cms.store') }}">
                                            @csrf
                                            <fieldset>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message210') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <select class="form-control" name="page" id="page" required>
                                                                <option value="">--@lang('admin.message211')--</option>
                                                                @foreach($pages as $page)
                                                                    <option value="{{ $page->slug }}">{{ $page->page }}</option>
                                                                @endforeach
                                                            </select>
                                                            @if ($errors->has('page'))
                                                                <label class="danger">{{ $errors->first('page') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message213') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <select class="form-control" name="application"
                                                                    id="application" required>
                                                                <option value="2">Driver</option>
                                                                <option value="1">User</option>
                                                            </select>
                                                            @if ($errors->has('application'))
                                                                <label class="danger">{{ $errors->first('application') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="lastName3">
                                                                @lang('admin.message212') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="title"
                                                                   name="title" placeholder="@lang('admin.message212')"
                                                                   required>
                                                            @if ($errors->has('title'))
                                                                <label class="danger">{{ $errors->first('title') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message214') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <textarea class="summernote" id="description"
                                                                      name="description" rows="3"
                                                                      placeholder="@lang('admin.description')"></textarea>
                                                            @if ($errors->has('description'))
                                                                <label class="danger">{{ $errors->first('description') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>


                                            </fieldset>
                                            <div class="form-actions right">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fa fa-check-square-o"></i> Save
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
@endsection

Milkrun/Web(Backend)/resources/views/admin/cms/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <link rel="stylesheet" type="text/css" href="{{ asset('merchanttheme/css/summernote.css') }}">
    <div class="app-content content">
        <div class="content-wrapper">

            <div class="content-header row">
                <div class="content-header-left col-md-10 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.message371')
                        (@lang('admin.message460') {{ strtoupper(Config::get('app.locale')) }})</h3>
                </div>
                <div class="content-header-right col-md-2 col-12">
                    <div class="btn-group float-md-right">
                        <a href="{{ route('cms.index') }}">
                            <button type="button" class="btn btn-icon btn-success mr-1"><i class="fa fa-reply"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            @if(session('cmsupdate'))
                <div class="box no-border">
                    <div class="box-tools">
                        <p class="alert alert-info alert-dismissible">
                            <strong>@lang('admin.message402')</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                        </p>
                    </div>
                </div>
            @endif


            <div class="content-body">
                <section id="validation">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <a class="heading-elements-toggle"><i class="ft-ellipsis-h font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                        <form method="POST" class="steps-validation wizard-notification"
                                              enctype="multipart/form-data"
                                              action="{{ route('cms.update',$cmspage->id) }}">
                                            {{method_field('PUT')}}
                                            @csrf
                                            <fieldset>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="lastName3">
                                                                @lang('admin.message212') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <input type="text" class="form-control" id="title"
                                                                   name="title" value="{{ $cmspage->LanguageSingle->title }}"
                                                                   placeholder="@lang('admin.message212')"
                                                                   required>
                                                            @if ($errors->has('title'))
                                                                <label class="danger">{{ $errors->first('title') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <div class="form-group">
                                                            <label for="emailAddress5">
                                                                @lang('admin.message214') :
                                                                <span class="danger">*</span>
                                                            </label>
                                                            <textarea class="summernote" id="description"
                                                                      name="description" rows="3"
                                                                      placeholder="@lang('admin.description')">{{ $cmspage->LanguageSingle->description }}</textarea>
                                                            @if ($errors->has('description'))
                                                                <label class="danger">{{ $errors->first('description') }}</label>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <div class="form-actions right">
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fa fa-check-square-o"></i> Save
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
@endsection

Milkrun/Web(Backend)/resources/views/admin/cms/index.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-8 col-12 mb-2">
                    <h3 class="content-header-title mb-0 d-inline-block">@lang('admin.message208')</h3>
                </div>

                <div class="content-header-right col-md-4 col-12">
                    <div class="btn-group float-md-right">
                        <div class="heading-elements">
                            <a title="@lang('admin.message209')" href="{{route('cms.create')}}">
                                <button class="btn btn-icon btn-success mr-1"><i
                                            class="fa fa-plus"></i>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">

                <section id="horizontal">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">

                                <div class="">
                                    <form method="post" action="{{ route('admin.cms.search') }}">
                                        @csrf
                                        <div class="table_search">
                                            <div class="col-md-2 col-xs-12 form-group ">
                                                <div class="input-group">
                                                    <input type="text" id="" name="pagetitle"
                                                           placeholder="@lang('admin.message373')"
                                                           class="form-control col-md-12 col-xs-12">
                                                </div>
                                            </div>


                                            <div class="col-sm-2  col-xs-12 form-group ">
                                                <button class="btn btn-primary" type="submit" name="seabt12"><i
                                                            class="fa fa-search" aria-hidden="true"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="card-content collapse show">
                                    <div class="">
                                        <table class="table display nowrap table-striped table-bordered scroll-horizontal">
                                            <thead>
                                            <tr>
                                                <th>@lang('admin.message213')</th>
                                                <th>@lang('admin.message212')</th>
                                                <th>@lang('admin.message214')</th>
                                                <th>@lang('admin.action')</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($cmspages as $cmspage)
                                                <tr>
                                                    <td>
                                                        @if($cmspage->application == 1)
                                                            User
                                                        @else
                                                            Driver
                                                        @endif

                                                    </td>
                                                    <td>@if(empty($cmspage->LanguageSingle))
                                                            <span style="color:red">{{ trans('admin.name-not-given') }}</span>
                                                            <span class="text-primary">( In {{ $cmspage->LanguageAny->LanguageName->name }}
                                                                : {{ $cmspage->LanguageAny->title }}
                                                                )</span>
                                                        @else
                                                            {{ $cmspage->LanguageSingle->title }}
                                                        @endif
                                                    </td>
                                                    <td>@if(empty($cmspage->LanguageSingle))
                                                            <span style="color:red">{{ trans('admin.name-not-given') }}</span>
                                                            <span class="text-primary">( In {{ $cmspage->LanguageAny->LanguageName->name }}
                                                                : {{ substr($cmspage->LanguageAny->description, 0, 70) }}
                                                                )</span>
                                                        @else
                                                            {{ substr($cmspage->LanguageSingle->description, 0, 70) }}
                                                        @endif
                                                    </td>

                                                    <td>
                                                        <a href="{{ route('cms.edit',$cmspage->id) }}"
                                                           data-original-title="Edit" data-toggle="tooltip"
                                                           data-placement="top"
                                                           class="btn menu-icon btn_edit action_btn"> <i
                                                                    class="fa fa-pencil"></i> </a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>

                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </section>

            </div>
        </div>
    </div>
@endsection