Milkrun/Web(Backend)/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Admin Routes

Route::prefix('admin')->group(function () {
    Route::get('/', ['as' => 'admin.login', 'uses' => 'Auth\AdminLoginController@showLoginForm']);
    Route::post('/login', ['as' => 'admin.login.submit', 'uses' => 'Auth\AdminLoginController@login']);
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@index']);
        Route::get('/change-language/{locale}', ['as' => 'admin.language', 'uses' => 'Admin\AdminController@SetLangauge']);
        Route::get('/logout', ['as' => 'admin.logout', 'uses' => 'Auth\AdminLoginController@logout']);
        Route::resource('documents', 'Admin\DocumentController');
        Route::post('document/update', ['as' => 'doc.update', 'uses' => 'Admin\DocumentController@update']);
        Route::resource('cms', 'Admin\CmsPagesController');
        Route::post('/cms/search', ['as' => 'admin.cms.search', 'uses' => 'Admin\CmsPagesController@Search']);

        Route::resource('promotions', 'Admin\PromotionNotificationController');
        Route::post('/promotions/search', ['as' => 'promotions.search', 'uses' => 'Admin\PromotionNotificationController@Search']);

        Route::get('/onesignal', ['as' => 'onesignal.index', 'uses' => 'Admin\AdminController@OneSignal']);
        Route::post('/onesignal', ['as' => 'onesignal.store', 'uses' => 'Admin\AdminController@UpdateOneSignal']);

        Route::get('/customer_support', ['as' => 'customer_support.index', 'uses' => 'Admin\AdminController@Customer_Support']);
        Route::post('/customer_support', ['as' => 'customer_support.search', 'uses' => 'Admin\AdminController@Customer_Support_Search']);

//Retailer
        Route::resource('retailer', 'Admin\RetailerController');
        Route::get('/retailer/wallet/{id}', ['as' => 'retailer.wallet', 'uses' => 'Admin\RetailerController@Wallet']);
        Route::post('/retailer/addmoney', ['as' => 'retailer.add.wallet', 'uses' => 'Admin\RetailerController@AddWalletMoney']);
        Route::get('/retailer/active/deactive/{id}/{status}', ['as' => 'retailer.active-deactive', 'uses' => 'Admin\RetailerController@ChangeStatus']);
        Route::post('/search/retailer', ['as' => 'retailer.search', 'uses' => 'Admin\RetailerController@Serach']);

//Driver
        Route::resource('drivers', 'Admin\DriverController');
        Route::get('/driver/wallet/{id}', ['as' => 'driver.wallet', 'uses' => 'Admin\DriverController@Wallet']);
        Route::post('/driver/addmoney', ['as' => 'driver.add.wallet', 'uses' => 'Admin\DriverController@AddWalletMoney']);
        Route::get('/driver/active/deactive/{id}/{status}', ['as' => 'driver.active-deactive', 'uses' => 'Admin\DriverController@ChangeStatus']);
        Route::post('/search/driver', ['as' => 'driver.search', 'uses' => 'Admin\DriverController@Serach']);

//Customer
        Route::resource('customers', 'Admin\CustomersController');
        Route::get('/customer/wallet/{id}', ['as' => 'customer.wallet', 'uses' => 'Admin\CustomersController@Wallet']);
        Route::post('/customer/addmoney', ['as' => 'customer.add.wallet', 'uses' => 'Admin\CustomersController@AddWalletMoney']);
        Route::get('/customer/active/deactive/{id}/{status}', ['as' => 'customer.active-deactive', 'uses' => 'Admin\CustomersController@ChangeStatus']);
        Route::post('/search/customer', ['as' => 'customer.search', 'uses' => 'Admin\CustomersController@Serach']);

//OrdersManagement
            Route::resource('orders', 'Admin\OrderManagementController');

//Station
        Route::resource('stations', 'Admin\StationController');
        Route::get('/station/wallet/{id}', ['as' => 'station.wallet', 'uses' => 'Admin\StationController@Wallet']);
        Route::post('/station/addmoney', ['as' => 'station.add.wallet', 'uses' => 'Admin\StationController@AddWalletMoney']);
        Route::get('/station/active/deactive/{id}/{status}', ['as' => 'station.active-deactive', 'uses' => 'Admin\StationController@ChangeStatus']);
        Route::post('/search/station', ['as' => 'station.search', 'uses' => 'Admin\StationController@Serach']);

//Station
        Route::resource('measurements', 'Admin\MeasurementController');
        Route::get('/measurement/wallet/{id}', ['as' => 'measurement.wallet', 'uses' => 'Admin\MeasurementController@Wallet']);
        Route::post('/measurement/addmoney', ['as' => 'measurement.add.wallet', 'uses' => 'Admin\MeasurementController@AddWalletMoney']);
        Route::get('/measurement/active/deactive/{id}/{status}', ['as' => 'measurement.active-deactive', 'uses' => 'Admin\MeasurementController@ChangeStatus']);
        Route::post('/search/measurement', ['as' => 'measurement.search', 'uses' => 'Admin\MeasurementController@Serach']);

    });
});


Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Milkrun/Web(Backend)/resources/views/admin/layouts/footer.blade.php
<footer class="footer footer-static footer-light navbar-border">
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">Copyright  &copy; 2018 <a class="text-bold-800 grey darken-2" href="#" >ApporioTaxi </a>, All rights reserved. </span><span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Hand-crafted & Made with <i class="ft-heart pink"></i></span></p>
</footer>


<script src="{{ asset('js/vendor.min.js') }}" type="text/javascript"></script>

<script src="{{ asset('js/menu.js') }}/" type="text/javascript"></script>
<script src="{{ asset('js/themeapp.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/datatables.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/select2.full.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/datedropper.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/jquery.validate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/summernote.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/jquery-clock-timepicker.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/my-script.js') }}" type="text/javascript"></script>

</body>
</html>

Milkrun/Web(Backend)/resources/views/admin/layouts/main.blade.php
@include('admin.layouts.nav')
@include('admin.layouts.sidebar')
@yield('content')
@include('admin.layouts.footer')

Milkrun/Web(Backend)/resources/views/admin/layouts/nav.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="ApporioTaxi">
    <meta name="keywords" content="ApporioTaxi">
    <title>{{ Auth::user()->name }}</title>
    <link rel="icon" href="{{ asset('images/favicon.png') }}">
    <link rel="icon" type="image/x-icon" href="{{ asset('images/favicon.png') }}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,400,500,700"
          rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{ asset('css/vendor.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/themeapp.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/gradient.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('fonts/meteocons/style.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/datatables.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/datedropper.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
</head>
<div id="loader1" class="loader1" style="display: none"></div>
<body class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar" data-open="click"
      data-menu="vertical-menu" data-col="2-columns">
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a
                            class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                                class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item"><a class="navbar-brand" href="{{route('admin.dashboard')}}"><img class="brand-logo"
                                                                                                      alt="admin logo"
                                                                                                      src="{{ asset('images/logo-1.png') }}">
                        <h3 class="brand-text">{{ Auth::user()->name }}</h3></a></li>
                <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse"
                                                  data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs"
                                                              href="#"><i class="ft-menu"> </i></a></li>

                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i
                                    class="ficon ft-maximize"></i></a></li>
                </ul>

                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-language nav-item">

                        <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false"><span>@lang('admin.language')
                                ({{ strtoupper(App::getLocale()) }})</span><span
                                    class="selected-language"></span></a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-flag">
                            @foreach($languages as $language)
                                <a class="dropdown-item selected-language"
                                   href="{{ route('admin.language',$language->locale) }}">{{ $language->name }}</a>
                                {{--{{ route('admin.langauge','en') }}--}}
                            @endforeach

                        </div>
                    </li>
                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link"
                                                                   href="#" data-toggle="dropdown"><span
                                    class="avatar avatar-online"><img
                                        src="{{ asset('images/logo-1.png') }}"
                                        alt="avatar"><i></i></span><span
                                    class="user-name">{{ Auth::user()->name }}</span></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('admin.logout') }}"><i class="ft-power"></i>
                                Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

Milkrun/Web(Backend)/resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-dark menu-accordion    menu-shadow " data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

            <li class="nav-item"><a href="{{ route('admin.dashboard') }}"><i class="icon-globe"></i><span
                        class="menu-title">@lang('admin.message43')</span></a></li>

            <li class=" nav-item"><a href="#"><i class="fa fa-user-secret"></i><span class="menu-title"
                                                                                     data-i18n="nav.adminMangement.main">@lang('admin.sub-admin')</span></a>
                <ul class="menu-content">
                    <li><a class="menu-item" href="#"
                           data-i18n="nav.active_ride.1_column">@lang('admin.message401')</a>
                    </li>


                    <li><a class="menu-item" href="#"
                           data-i18n="nav.active_ride.1_column">@lang('admin.role')</a>
                    </li>

                </ul>
            </li>


            <li class="nav-item"><a
                    href="{{ route('drivers.index') }}"><i class="icon-key"></i><span
                        class="menu-title">@lang('admin.DriverManagement')</span></a>
            </li>

            <li class="nav-item"><a
                    href="{{ route('customers.index') }}"><i class="icon-graduation"></i><span
                        class="menu-title">@lang('admin.melvin_customer_message1')</span></a>
            </li>

            <li class="nav-item"><a
                    href="{{ route('retailer.index') }}"><i class="icon-user"></i><span
                        class="menu-title">@lang('admin.melvin_sidebar_message1')</span></a>
            </li>

            <li class="nav-item"><a
                    href="{{ route('orders.index') }}"><i class="icon-organization"></i><span
                        class="menu-title">@lang('admin.melvin_order_message1')</span></a>
            </li>

            <li class="nav-item"><a
                    href="{{ route('stations.index') }}"><i class="fa fa-bell-o"></i><span
                        class="menu-title">@lang('admin.melvin_station_message1')</span></a></li>

            <li class="nav-item"><a
                    href="{{ route('measurements.index') }}"><i class="icon-settings"></i><span
                        class="menu-title">@lang('admin.melvin_measurement_message1')</span></a></li>

            <li class="nav-item"><a href="{{ route('documents.index') }}"><i class="fa fa-file"></i><span
                        class="menu-title">@lang('admin.melvin_sidebar_message2')</span></a></li>

            <li class="nav-item"><a
                    href="{{ route('onesignal.index') }}"><i class="fa fa-bell-o"></i><span
                        class="menu-title">@lang('admin.message85')</span></a></li>

            <li class="nav-item"><a
                    href="{{ route('promotions.index') }}"><i class="fa fa-bell-o"></i><span
                        class="menu-title">@lang('admin.message60')</span></a></li>

            <li class="nav-item"><a
                    href="{{ route('customer_support.index') }}"><i class="fa fa-headphones"></i><span
                        class="menu-title">@lang('admin.message379')</span></a></li>

            <li class="nav-item"><a href="{{ route('cms.index') }}"><i class="fa fa-columns"></i><span
                        class="menu-title">@lang('admin.message208')</span></a></li>


        </ul>
    </div>
</div>